class Solution {
    public String decodeString(String s) {
  
             Stack<String> stack=new Stack<>();
                     int num=0;
                             for(int i=0;i<s.length();i++)
                                     {
                                                 char c=s.charAt(i);
                                                          
                                                                        if(Character.isDigit(c))
                                                                                    {
                                                                                                 num=num*10+(c-'0');
                                                                                                               
                                                                                                                           }
                                                                                                                                       else if(c=='[')
                                                                                                                                                   {
                                                                                                                                                               stack.push(String.valueOf(num));
                                                                                                                                                                             num=0;  
                                                                                                                                                                                           stack.push("[");
                                                                                                                                                                                                       }
                                                                                                                                                                                                                   else if(Character.isLetter(c)) 
                                                                                                                                                                                                                               {
                                                                                                                                                                                                                                               int index=i;
                                                                                                                                                                                                                                                               while(index<s.length()&&Character.isLetter(s.charAt(index))) 
                                                                                                                                                                                                                                                                               {
                                                                                                                                                                                                                                                                                                   index++; 
                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                   stack.push(s.substring(i,index));
                                                                                                                                                                                                                                                                                                                                                   i=index-1;
                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                         else if(c==']')
                                                                                                                                                                                                                                                                                                                                                                                                                     {
                                                                                                                                                                                                                                                                                                                                                                                                                                     String r="";
                                                                                                                                                                                                                                                                                                                                                                                                                                                     while(!stack.isEmpty()&&!stack.peek().equals("["))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         r=stack.pop()+r;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         stack.pop();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         int num1=Integer.parseInt(stack.pop());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         String temp="";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         for(int j=1;j<=num1;j++)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             temp+=r;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             stack.push(temp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      String result = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              while (!stack.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          result = stack.pop() + result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }